---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: golang:1.15
  environment:
      GOPROXY: https://goproxy.cn
  commands:
  - make clean
  - make lint
  - make fmt-check
  - make misspell-check
  - make test-vendor
  - make build
  when:
    event:
    - push
    - tag
    - pull_request

- name: unit-test
  image: golang:1.15
  commands:
  - make unit-test-coverage
  settings:
    group: test
  when:
    branch:
    - main
    event:
    - push
    - pull_request

- name: release-test
  image: golang:1.15
  commands:
  - make test
  settings:
    group: test
  when:
    branch:
    - "release/*"
    event:
    - push
    - pull_request

- name: tag-test
  pull: always
  image: golang:1.15
  commands:
  - make test
  settings:
    group: test
  when:
    event:
    - tag

#- name: static
#  image: golang:1.15
#  environment:
#    GOPROXY: https://goproxy.cn
#  commands:
#  - export PATH=$PATH:$GOPATH/bin
#  - make release
#  when:
#    event:
#    - push
#    - tag
#
